# Generated by Django 2.2.2 on 2019-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190901_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='room_number',
            field=models.CharField(max_length=11, verbose_name='room number'),
        ),
    ]
